install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v0.9.2/gnatsd-v0.9.2-windows-386.zip
  - 7z e gnatsd-v0.9.2-windows-386.zip gnatsd.exe -r -oc:\projects\csnats\build
  - cmd: set PATH=%PATH%;C:\projects\csnats\build
before_build:
  - nuget restore
build:
  project: NATS.sln
notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: XI9j+cGG2z/YLFNk+KCnLQ==
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})”
